### ISSUE TITLE
Sorting buttons should be able to sort ascending/descending/none

### ISSUE THREAD

**Issue by Codeshark-NET** [protontypes/climate-triage#30]
As a user, when clicking a sorting-button, it should toggle between 3 states of:
- Ascending
- Descending
- None (removing the sorting)

This way, we can effectively turn the sorting into just 3 buttons:
- By issue age
- By downloads
- By stars

& remove the "none" button

**Comment by Ly0n** [comment]
I'm not sure how many users really need this in the end. Perhaps most likely for Issue Age, but not so much for the download numbers or the stars. 

I suppose your underlying intention here is to give small projects more visibility.Which I think could definitely be improved!That's why a 'None', which I'd prefer to rename 'Random', is very important.Another way to archive this sorting is by latest issue and perhaps project age, as suggested here.   The latest issues should also make the smaller projects visible, but big strong projects just have a high frequency of new issues, so smaller projects will also get lost here. Another way to archive so that smaller projects are more visible is to sort by project age, as suggested here: #31

**Comment by andrew** [comment]
PR: https://github.com/protontypes/climate-triage/issues/30
